# Generated by Django 5.1.5 on 2025-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_evento_expositor_ticket_ubicacion_delete_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
