# Generated by Django 5.1.5 on 2025-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticket_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
