# Generated by Django 5.1.5 on 2025-01-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_evento_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.TextField(max_length=255),
        ),
    ]
