# Generated by Django 5.1.5 on 2025-01-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_evento_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion'),
        ),
    ]
