# Generated by Django 5.1.5 on 2025-01-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizador'), ('ASSISTANT', 'Asistente')], default='ASSISTANT', max_length=10),
        ),
    ]
